"""initial_migration_add_lat_lon

Revision ID: e8ca74a4cf06
Revises: 
Create Date: 2025-11-21 14:47:03.637600

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'e8ca74a4cf06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'users' not in tables:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('news',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('fuente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('climate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('temperatura', sa.Float(), nullable=True),
        sa.Column('humedad', sa.Float(), nullable=True),
        sa.Column('precipitacion', sa.Float(), nullable=True),
        sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('crops',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('latitud', sa.Float(), nullable=True),
        sa.Column('longitud', sa.Float(), nullable=True),
        sa.Column('fecha_registro', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('severidad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('crop_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('crop_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###
    else:
        # If tables exist, we just add the new columns if they are missing
        if 'crops' in tables:
            columns = [c['name'] for c in inspector.get_columns('crops')]
            if 'latitud' not in columns:
                op.add_column('crops', sa.Column('latitud', sa.Float(), nullable=True))
            if 'longitud' not in columns:
                op.add_column('crops', sa.Column('longitud', sa.Float(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('alerts')
    op.drop_table('reports')
    op.drop_table('crops')
    op.drop_table('climate')
    op.drop_table('users')
    op.drop_table('news')
    # ### end Alembic commands ###
